[tool.poetry]
name = "carrier.dhl_express"
version = "2021.10rc0"
description = "DHL Express Web API Schemas Python Data Types library"
repository="https://github.com/karrioapi/karrio"
homepage="https://github.com/karrioapi/karrio/tree/main/carrier.dhl_express"
authors = ["Karrio <hello@karrio.io>"]
license = "Apache-2.0"
readme = "README.md"
packages = [
    { include = "dhl_express_lib" }
]
classifiers = [
	"Intended Audience :: Developers",
	"Operating System :: OS Independent",
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: Apache Software License",
]

[tool.poetry.dependencies]
python = "^3.6"
jstruct = ""

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools!=50.0"]
build-backend = "poetry.core.masonry.api"
