apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-tls-proxy
data:
  stunnel.conf: |
    foreground = yes
    debug = info
    [redis-tls]
    client = yes
    accept = 127.0.0.1:6379
    connect = jtl-stg-redis.redis.cache.windows.net:6380
