[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "karrio_dpd"
version = "2026.1.12"
description = "Karrio - DPD Shipping Extension"
readme = "README.md"
requires-python = ">=3.7"
license = "LGPL-3.0"
authors = [
    {name = "karrio", email = "hello@karrio.io"}
]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "karrio",
]

[project.urls]
Homepage = "https://github.com/karrioapi/karrio"

[project.entry-points."karrio.plugins"]
dpd = "karrio.plugins.dpd:METADATA"

[tool.setuptools]
zip-safe = false
include-package-data = true

[tool.setuptools.package-dir]
"" = "."

[tool.setuptools.packages.find]
exclude = ["tests.*", "tests"]
namespaces = true
