[tool.poetry]
name = "purplship.dhl_poland"
version = "2021.11"
homepage="https://next.purplship.com/docs/guides/sdk"
repository="https://github.com/purplship/purplship"
description = "Purplship - DHL Parcel Poland Shipping Extension"
authors = ["Purplship <hello@purplship.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{ include = "purplship" }]
classifiers=[
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]

[tool.poetry.dependencies]
python = "^3.7"
"purplship" = ""
"carrier.dhl_poland" = ""

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools!=50.0"]
build-backend = "poetry.core.masonry.api"
