[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "karrio"
version = "2026.1.5"
description = "Multi-carrier shipping API integration with python"
readme = "README.md"
requires-python = ">=3.11"
license = "LGPL-3.0"
authors = [
    {name = "karrio", email = "hello@karrio.io"}
]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "attrs",
    "jstruct",
    "xmltodict",
    "lxml",
    "lxml-stubs",
    "py-soap",
    "Pillow",
    "phonenumbers",
    "python-barcode",
    "PyPDF2",
    "toml",
    "loguru",
]

[project.urls]
Homepage = "https://github.com/karrioapi/karrio"

[tool.setuptools]
zip-safe = false
include-package-data = true
packages = {find = {exclude = ["tests.*", "tests"]}}

[tool.setuptools.package-data]
"karrio.addons.fonts" = ["*.ttf", "*.otf", "*.woff", "*.woff2"]
"*" = ["*.ttf", "*.otf", "*.woff", "*.woff2", "*.json", "*.txt", "*.html", "*.css", "*.js"]
