[tool.poetry]
name = "carrier.purolator"
version = "2020.4.1"
description = "Purolator Web API Schemas Python Data Types library"
repository="https://github.com/karrio/karrio"
homepage="https://github.com/karrio/karrio/tree/main/carrier.purolator"
authors = ["Purplship <hello@karrio.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [
    { include = "purolator_lib" }
]
classifiers = [
	"Intended Audience :: Developers",
	"Operating System :: OS Independent",
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: Apache Software License",
]

[tool.poetry.dependencies]
python = "^3.6"
six = ""
lxml = ""

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools!=50.0"]
build-backend = "poetry.core.masonry.api"
