[tool.poetry]
name = "karrio.yanwen"
version = "2022.4"
homepage="https://karrio.io/docs/guides/sdk"
repository="https://github.com/karrio/karrio"
description = "Karrio - Yanwen Shipping Extension"
authors = ["Karrio <hello@karrio.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{ include = "karrio" }]
classifiers=[
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]

[tool.poetry.dependencies]
python = "^3.7"
"karrio" = ""
"carrier.yanwen" = ""

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools!=50.0"]
build-backend = "poetry.core.masonry.api"
