# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: platform-tests

on: [push]

permissions:
  contents: read

jobs:
  server-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
      - name: Run Tests
        env:
          ENABLE_ALL_PLUGINS_BY_DEFAULT: true
        run: |
          ./bin/setup-server-env -v &&
          ./bin/cli plugins list &&
          ./bin/migrate &&
          ./bin/run-server-tests -v

  platform-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - name: Install
        run: |
          npm install -g corepack
          mkdir -p ~/.volta/bin
          corepack enable --install-directory ~/.volta/bin
          npm install
      - name: Test Build
        run: |
          cp ee/apps/platform/.env.sample ee/apps/platform/.env
          npm run prisma:generate -w ee/apps/platform
          npm run build -w ee/apps/platform

  web-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - name: Install
        run: |
          npm install -g corepack
          mkdir -p ~/.volta/bin
          corepack enable --install-directory ~/.volta/bin
      - name: Test Build
        run: |
          npm ci
          npm run build -w apps/web
