# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: karrio-tests

on: [push]

jobs:
  sdk-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          pip install --upgrade pip
          ./bin/setup-sdk-env.sh &&
          ./bin/run-sdk-typecheck.sh &&
          ./bin/run-sdk-tests.sh
  server-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          sudo chown -R 1000 ./
          docker-compose -f docker-compose.test.yml run --rm karrio bash -c '
            cd app &&
            pip install --upgrade pip &&
            pip install -r requirements.dev.txt &&
            pip install -r requirements.server.dev.txt &&
            cd -
            karrio migrate &&
            karrio test --failfast karrio.server.proxy.tests &&
            karrio test --failfast karrio.server.pricing.tests &&
            karrio test --failfast karrio.server.manager.tests &&
            karrio test --failfast karrio.server.events.tests &&
            karrio test --failfast karrio.server.graph.tests &&
            karrio test --failfast karrio.server.orders.tests
          '
