# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: karrio-tests

on: [push]

jobs:
  sdk-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]

    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          ./bin/setup-sdk-env -v &&
          ./bin/run-sdk-typecheck &&
          ./bin/run-sdk-tests

  server-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]

    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          ./bin/setup-server-env -v &&
          ./bin/migrate &&
          ./bin/run-server-tests

  dashbaord-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - name: Install
        run: |
          npm install -g corepack
          mkdir -p ~/.volta/bin
          corepack enable --install-directory ~/.volta/bin
      - name: Test Build
        run: |
          npm ci
          npm run build -w apps/dashboard
